### ISSUE TITLE
Backport to Windows 10

### ISSUE THREAD

**Issue by Blue-Killer87** [morning4coffe-dev/recurrents#87]
Please ASAP, it's urgent and I need it now.

**Comment by morning4coffe-dev** [comment]
Thanks for reporting this. The correct versions are now uploaded to the Store, so the ball is on the Microsoft Store team now

**Comment by Blue-Killer87** [comment]
Thanks for the fix, tested it on 15 different PCs with windows 10 and worked every time.

**Comment by morning4coffe-dev** [comment]
Awesome! Thanks for testing, Jan 🚀
