### ISSUE TITLE
Translation casing

### ISSUE THREAD

**Issue by szv** [morning4coffe-dev/recurrents#99]
![grafik](https://github.com/morning4coffe-dev/recurrents/assets/10291845/5fb1c49c-861d-477d-b252-6d50bba10475)

The .ToLower() converts every letter to lower-case.
In the image above it shouldn't be _tage_, but _Tage_.

**Comment by szv** [comment]
Yeah German is sometimes strange 😅😅

**Comment by morning4coffe-dev** [comment]
This specific one should be [fixed](https://github.com/morning4coffe-dev/recurrents/commit/c3c2a4919a7cb3e1562fcfd3edf82ff1f774736c) now, again thanks for reporting 😇
